name: cab_rider
description: Cab Rider Mobile App, from Udemy Course

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  lint: ^1.8.2
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
